students = {
    1: {"name": "John", "age": 17, "year": "Year 12"},
    2: {"name": "Alice", "age": 18, "year": "Year 12"},
    3: {"name": "Michael", "age": 16, "year": "Year 11"},
    4: {"name": "Sophia", "age": 15, "year": "Year 10"},
    5: {"name": "David", "age": 19, "year": "Year 13"},
    6: {"name": "Emma", "age": 17, "year": "Year 12"},
    7: {"name": "Daniel", "age": 18, "year": "Year 12"},
    8: {"name": "Olivia", "age": 16, "year": "Year 11"},
    9: {"name": "James", "age": 15, "year": "Year 10"},
    10: {"name": "Sophia", "age": 19, "year": "Year 13"},
    11: {"name": "Lucas", "age": 17, "year": "Year 12"},
    12: {"name": "Mia", "age": 18, "year": "Year 12"},
    13: {"name": "Ethan", "age": 16, "year": "Year 11"},
    14: {"name": "Isabella", "age": 15, "year": "Year 10"},
    15: {"name": "Alexander", "age": 19, "year": "Year 13"},
    16: {"name": "Charlotte", "age": 17, "year": "Year 12"},
    17: {"name": "Benjamin", "age": 18, "year": "Year 12"},
    18: {"name": "Amelia", "age": 16, "year": "Year 11"},
    19: {"name": "William", "age": 15, "year": "Year 10"},
    20: {"name": "Harper", "age": 19, "year": "Year 13"},
}